# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonforgov', '0003_auto_20161116_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='GradeCode',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='\u7ea7\u522b\u5b9a\u4f4d'),
        ),
    ]
