# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonforgov', '0004_auto_20161117_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='AvailabilityCount',
            field=models.IntegerField(verbose_name='\u53ef\u79df\u8d41\u5355\u5143\u6570\u91cf'),
        ),
    ]
